# Generated by Django 5.2.1 on 2025-05-16 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="song",
            name="album",
        ),
        migrations.RemoveField(
            model_name="song",
            name="artist",
        ),
        migrations.AlterUniqueTogether(
            name="like",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="like",
            name="song",
        ),
        migrations.RemoveField(
            model_name="like",
            name="user",
        ),
        migrations.RemoveField(
            model_name="listeninghistory",
            name="song",
        ),
        migrations.RemoveField(
            model_name="listeninghistory",
            name="user",
        ),
        migrations.RemoveField(
            model_name="playlist",
            name="user",
        ),
        migrations.RemoveField(
            model_name="playlistsong",
            name="playlist",
        ),
        migrations.AlterUniqueTogether(
            name="playlistsong",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="playlistsong",
            name="song",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="song",
        ),
        migrations.RemoveField(
            model_name="recommendation",
            name="user",
        ),
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.RemoveField(
            model_name="user",
            name="user_permissions",
        ),
        migrations.DeleteModel(
            name="Album",
        ),
        migrations.DeleteModel(
            name="Artist",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.DeleteModel(
            name="ListeningHistory",
        ),
        migrations.DeleteModel(
            name="Playlist",
        ),
        migrations.DeleteModel(
            name="PlaylistSong",
        ),
        migrations.DeleteModel(
            name="Song",
        ),
        migrations.DeleteModel(
            name="Recommendation",
        ),
        migrations.DeleteModel(
            name="User",
        ),
    ]
